services:
  - type: web
    name: placement-management-system
    runtime: python
    buildCommand: "bash build.sh"
    startCommand: "gunicorn placement_system.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "placement-management-system.onrender.com"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://placement-management-system.onrender.com"
