# Generated by Django 5.2.14 on 2026-09-08 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('industry', models.CharField(default='IT Services', max_length=100)),
                ('location', models.CharField(default='Bangalore', max_length=100)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='PlacementDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job Role (e.g., Python Developer)', max_length=150)),
                ('job_description', models.TextField()),
                ('package_lpa', models.DecimalField(decimal_places=2, help_text='Package in LPA (e.g., 6.5)', max_digits=5)),
                ('drive_date', models.DateField()),
                ('deadline', models.DateField()),
                ('vacancies', models.IntegerField(default=10)),
                ('min_cgpa', models.DecimalField(decimal_places=2, default=6.0, max_digits=4)),
                ('max_backlogs', models.IntegerField(default=0)),
                ('allowed_departments', models.CharField(default='CSE, IT, ECE, MCA', help_text='Comma-separated departments', max_length=200)),
                ('target_graduation_year', models.IntegerField(default=2025)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Upcoming', 'Upcoming'), ('Closed', 'Closed')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('department', models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Communication Engineering'), ('MCA', 'Master of Computer Applications'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering')], default='CSE', max_length=50)),
                ('college', models.CharField(default='XYZ College', max_length=100)),
                ('graduation_year', models.IntegerField(default=2025)),
                ('cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('backlogs', models.IntegerField(default=0)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated skills (e.g., Python, SQL, Java)')),
                ('certifications', models.TextField(blank=True, help_text='List of certifications')),
                ('projects', models.TextField(blank=True, help_text='Key projects')),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Shortlisted', 'Shortlisted'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.placementdrive')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'drive')},
            },
        ),
    ]
