# Generated by Django 5.2.14 on 2026-09-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload company logo image', null=True, upload_to='company_logos/'),
        ),
    ]
