# Generated by Django 5.2.14 on 2026-09-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementdrive',
            name='required_skills',
            field=models.CharField(default='Python, SQL', help_text='Comma-separated required skills (e.g., Python, SQL, Java)', max_length=255),
        ),
    ]
