# Generated by Django 5.2.14 on 2026-09-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_placementdrive_required_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science & Engineering'), ('IT', 'Information Technology'), ('ECE', 'Electronics & Communication Engineering'), ('MCA', 'Master of Computer Applications'), ('ME', 'Mechanical Engineering'), ('CE', 'Civil Engineering'), ('OTHER', 'Other / Others')], default='CSE', max_length=50),
        ),
    ]
